/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { messageType } from "./components/j-message/j-message";
export namespace Components {
    interface JMessageBox {
    }
    interface JMessageItem {
        "close": () => Promise<void>;
        "setTitle": (title: string) => Promise<void>;
        "setType": (type: messageType) => Promise<void>;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        "message": () => Promise<void>;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLJMessageBoxElement extends Components.JMessageBox, HTMLStencilElement {
    }
    var HTMLJMessageBoxElement: {
        prototype: HTMLJMessageBoxElement;
        new (): HTMLJMessageBoxElement;
    };
    interface HTMLJMessageItemElement extends Components.JMessageItem, HTMLStencilElement {
    }
    var HTMLJMessageItemElement: {
        prototype: HTMLJMessageItemElement;
        new (): HTMLJMessageItemElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "j-message-box": HTMLJMessageBoxElement;
        "j-message-item": HTMLJMessageItemElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface JMessageBox {
    }
    interface JMessageItem {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "j-message-box": JMessageBox;
        "j-message-item": JMessageItem;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "j-message-box": LocalJSX.JMessageBox & JSXBase.HTMLAttributes<HTMLJMessageBoxElement>;
            "j-message-item": LocalJSX.JMessageItem & JSXBase.HTMLAttributes<HTMLJMessageItemElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
